### ISSUE TITLE
A Dispatch subscribed to a datarule does not seem to work, sets subscribe to null

### ISSUE THREAD

**Issue by maanenson** [exosite/exoline#117]
$ exo spec CIK spec.yaml --create
Running spec on: CIK
dispatch_timeout_push_event not found.
Creating dispatch with name: Cloud - Timeout Push Dispatch, alias: dispatch_timeout_push_event, method: http_post, recipient: https://something.exosite.com/
$ exo spec CIK spec.yaml
Running spec on: CIK
spec expects subscribe for dispatch_timeout_push_event to be 19a78ddbbb9bc1ae22e370b583a7048263ed4f24, but they are not.
$ exo info CIK dispatch_timeout_push_event --pretty
{
    "basic": {
        "modified": 1436473754,
        "status": "normal",
        "subscribers": 0,
        "type": "dispatch"
    },
    "comments": [],
    "description": {
        "format": "string",
        "locked": false,
        "message": "message",
        "meta": "",
        "method": "http_post",
        "name": "Cloud - Timeout Push Dispatch",
        "preprocess": [],
        "public": false,
        "recipient": "https://something.exosite.com/",
        "retention": {
            "count": 10,
            "duration": "infinity"
        },
        "subject": "",
        "subscribe": null
    },
    "shares": [],
    "storage": {
        "count": 0,
        "first": 0,
        "last": 0,
        "size": 0
    },
    "subscribers": [],
    "tags": []
}

**Comment by dweaver** [comment]
Could you share your spec file, Mike?
