### ISSUE TITLE
exo twee <INVALID_CIK>

### ISSUE THREAD

**Issue by asolz** [exosite/exoline#136]
Running this command now throws an exception of 'type error' rather than a 1P message about the CIK.

**Comment by dweaver** [comment]
I need an example of <INVALID_CIK>. It works for me
```
$ exo -v
Exosite Command Line 0.9.21
$ exo twee 2262c45567f35451b9e0d44e6bac634e9b243ef3
One Platform exception: {u'message': u'Authorization failed', u'code': 401}
```

**Comment by asolz** [comment]
I updated to 0.9.23 and it stopped happening. Maybe it was some partial change leftover from the hackathon.
