### ISSUE TITLE
Query command

### ISSUE THREAD

**Issue by dweaver** [exosite/exoline#150]
Since it's a complex command I'd suggest we provide some simple default behavior similar to `find`, but also support passing RPC arguments in explicitly with `-`.

```
$ exo query --help
Query resources

Usage:
  exo [options] query <cik> [<rid>] [-]

Options:
  --filter=<filters>      property filters as JSON, e.g. '{"model": "mymodel"}'
  --select=<prop1,prop2>  properties to include in results [default: rid]
  --limit=<count>         number of results to return
  --cursor=<rid>          last RID in previous result set
  --format=(json|csv)     format of output [default:json]
```

Output is JSON response, e.g.:

```
$ exo query <cik> <rid> --filter='{"depth": 1, "status": "expired"}' --select=rid,name --limit=3
{"matches":[{"rid":"0005a9c98208fcc16d5ccabbf97202ee5975015d","name":"Community"},{"rid":"00073c1b9b79b0848bc8000a20d5da73a22c471b","name":"arduino"},,{"rid":"013df6c804defb903f3748ba9d3b77909d06071a","name":"Exosite Device"}],"cursor":{"rid":"013df6c804defb903f3748ba9d3b77909d06071a"},"count":3}}]
```

Example of the other form:

```
$ echo '[{"status": "expired"}, {"name": true, "rid": true}, {}]' | exo query <cik> <rid>
...
```

@ophentis, @willcharlton, @tadpol, @asolz what do you think? The thing I like least about this is `--filter='{"status":"expired"}'`. It seems a bit verbose for something simple. On the other hand, if it were `filter status=expired` then we have to switch back to JSON for anything the syntax doesn't cover, and invent syntax for other things like $neq, $and, $or. Any ideas how to make simple things easier?

**Comment by asolz** [comment]
Writing JSON on the command line is a huge pain. 

I don't think inventing our own syntax is a horrible idea, but someone has probably done this before.

I like using command line switches (and maybe ordering) to determine what the query is, but there might be a way to simplify it.

    $ exo query <cik> <rid> --filter --depth=1 --status=expired --select=rid,name --query --model = mymodel --status = !expired --or --name = !andrews_test

That might be annoying to remember how to use, but I'd prefer not to do JSON there since it's prone to errors. Another option could be to have a separate exoline command for generating the query.

    $ exo querygen --select=rid --filter --model=mymodel --or --status= !expired | exo query <cik> <rid>

**Comment by willcharlton** [comment]
I agree with Andrew that's the piping JSON on the on the command line is the worst. If that's the way we went, I would just end up doing stuff like this:

`cat ~/.exoline/queries/<domain>/<model>/<query_file>.exql | exo query <cik> <rid> -`

or

`cat ~/.exoline/queries/<domain>/<alias>/<query_file>.exql | exo query <cik> <rid> -`

Where I would just create query files or yaml files with queries in them that I can format (indent) then re-format them for cli piping into exoline. 

This would also make the cli options fewer and easier to understand: `--format` would basically be all that's left...

That makes me want to recommend establishing a query file system as I've described above. I would not be in favor of having an exoline-based query builder for piping back into exoline as this would be creating two plugins to accomplish a single purpose. If anything the `exo query` command could dump out examples like the spec command does. 

I would also be in favor of using an SQL syntax, but I also realize this would be difficult to implement. My vote would be for query files. This would also be useful for sharing common queries with customers if they're exoline savvy.

Thoughts?

Thanks.

**Comment by dweaver** [comment]
@asolz I agree writing JSON at the command line is a pain and options are friendlier. Having a query generator is a good idea since then you don't have to start from scratch if you want to use some advanced feature that doesn't yet have a friendly option. Maybe one command could do both, where a `query --generate` option would generate something that could be piped back into the command. Supported operators we'd want to consider CLI-friendly options for: `$and, $or, $nor, $eq, $gt, $gte, $lt, $lte, $ne, $in, $nin, $not, $glob`.

@willcharlton I think support for query files is going to be needed no matter what, so you can use the latest and greatest query features easily. Does the `-` option pretty much cover the part Exoline would need to do for file support as you're describing it? 

Maybe we support a subset of operators (similar to `find` now) at the start, a `--generate` option, and full support for JSON query files with `-`.

**Comment by willcharlton** [comment]
I would say that if you're using a query file then you *don't* use the `-` to signify read-from-stdin. Instead you'd use a `--queryfile=path/to/query_file.exql`. Then the logic that opens the query file could also do some things to the query JSON blob such as strip out indentation. Supporting a subset or common query operators is a great idea for running a quick query or developing one.

**Comment by dweaver** [comment]
For reference, here's a basic query using curl.

```
CIK=$1

curl 'https://m2.exosite.com:443/onep:v1/rpc/process' -X POST -m 60 -H 'Connection: keep-alive' -H 'Content-Type: application/json; charset=utf-8' -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'User-Agent: Exoline 0.9.25' -d '{"calls": [{"id": 0, "procedure": "query", "arguments": [{"alias":""}, {}, {"rid":true}, {} ] }], "auth": {"cik": "'$CIK'"}}'
```
