### ISSUE TITLE
"twee" aborting when printing value of Boolean dataport

### ISSUE THREAD

**Issue by EmDV** [exosite/exoline#91]
*Note* tree with option --value does not halt on the same type of dataport. Investigate by finding a dataport with the 'Binary' type.

**Comment by EmDV** [comment]
Roving WiFi Enabled Device      cl cik: <Last four of deviceCIK>9661e
  │   │       │   ├─ADC Value    dp.i adc: 0 (2 years ago)
  │   │       │   ├─Current      dp.f current: 20 (2 years ago)
Traceback (most recent call last):
  File "/usr/local/bin/exo", line 2765, in <module>
    sys.exit(cmd(sys.argv))
  File "/usr/local/bin/exo", line 2701, in cmd
    handle_args(cmd, args)
  File "/usr/local/bin/exo", line 2446, in handle_args
    er.tree(cik, cli_args=args)
  File "/usr/local/bin/exo", line 1344, in tree
    self.tree({'cik': cik, 'client_id': rid}, info['aliases'], cli_args, child_spacer, level=level + 1, info_options=info_options)
  File "/usr/local/bin/exo", line 1344, in tree
    self.tree({'cik': cik, 'client_id': rid}, info['aliases'], cli_args, child_spacer, level=level + 1, info_options=info_options)
  File "/usr/local/bin/exo", line 1344, in tree
    self.tree({'cik': cik, 'client_id': rid}, info['aliases'], cli_args, child_spacer, level=level + 1, info_options=info_options)
  File "/usr/local/bin/exo", line 1344, in tree
    self.tree({'cik': cik, 'client_id': rid}, info['aliases'], cli_args, child_spacer, level=level + 1, info_options=info_options)
  File "/usr/local/bin/exo", line 1346, in tree
    self._print_node(rid, info, aliases, cli_args, own_spacer, islast, maxlen, values=info['read'] if 'read' in info else None)
  File "/usr/local/bin/exo", line 1198, in _print_node
    displaytype += '.' + {'string': 's', 'float': 'f', 'integer': 'i'}[info['description']['format']]
KeyError: u'binary'
martindavis@martindavis-OptiPlex-390:~/reporting$

**Comment by dweaver** [comment]
That was fixed a couple of versions ago. Try grabbing the latest version:

```
$ pip install --upgrade exoline
```

**Comment by EmDV** [comment]
That did the trick. Thanks.
