### ISSUE TITLE
Support setting protected flag when adding content

### ISSUE THREAD

**Issue by ryankucera** [exosite/exoline#92]
I should be able to optionally set the protected flag on a content entry when using content put command. 

e.g. 
`~ ryankucera$ exo content put M1 M1FW2 ./2.fw --meta=exolinetest --protected=true`

**Comment by dweaver** [comment]
Looks like that's missing from the Python library, too. I'll get it in there shortly.

**Comment by dweaver** [comment]
`--protected` flag is in pyonep and exline 0.9.7
