### ISSUE TITLE
Add support for setting client limits with spec command

### ISSUE THREAD

**Issue by dweaver** [exosite/exoline#96]
The spec could look like this:
```
description:
    limits:
    -  dataports: 4
...
```

Updating description for a client requires owner permissions, so if --create was passed then to update a device you'd need --portal and to update a portal you'd need --domain.

**Comment by dweaver** [comment]
This should also also support setting other description items, like retention.

**Comment by tadpol** [comment]
Retention is already supported.

**Comment by dweaver** [comment]
supported in 0.9.18
